const productData = [
  {
    id: 1,
    category:"Perfume",
    img: "images/1.jpg",
    title: "Card 1 Title",
    description: "This is a description for Card 1",
    email: "example@email.com",
  },
  {
    id: 2,
    category:"Perfume",
    img: "images/2.jpg",
    title: "Card 2 Title",
    description: "This is a description for Card 2",
    email: "example@email.com",
  },
  {
    id: 3,
    category:"Perfume",
    img: "images/3.jpg",
    title: "Card 3 Title",
    description: "This is a description for Card 3",
    email: "example@email.com",
  },
  {
    id: 4,
    category:"Perfume",
    img: "images/4.jpg",
    title: "Card 4 Title",
    description: "This is a description for Card 4",
    email: "example@email.com",
  },
  {
    id: 5,
    category:"Perfume",
    img: "images/5.jpg",
    title: "Card 5 Title",
    description: "This is a description for Card 5",
    email: "example@email.com",
  },
  {
    id: 6,
    category:"Perfume",
    img: "images/6.jpg",
    title: "Card 6 Title",
    description: "This is a description for Card 5",
    email: "example@email.com",
  },
  {
    id: 7,
    category:"Perfume",
    img: "images/7.jpg",
    title: "Card 7 Title",
    description: "This is a description for Card 5",
    email: "example@email.com",
  },
  {
    id: 8,
    category:"Perfume",
    img: "images/8.jpg",
    title: "Card 8 Title",
    description: "This is a description for Card 5",
    email: "example@email.com",
  },
  {
    id: 9,
    category:"Accessories",
    img: "images/acc/1.jpg",
    title: "Card 9 Title",
    description: "This is a description for Card 1",
    email: "example@email.com",
  },
  {
    id: 10,
    category:"Accessories",
    img: "images/acc/2.jpg",
    title: "Card 10 Title",
    description: "This is a description for Card 2",
    email: "example@email.com",
  },
  {
    id: 11,
    category:"Accessories",
    img: "images/acc/3.jpg",
    title: "Card 11 Title",
    description: "This is a description for Card 3",
    email: "example@email.com",
  },
  {
    id: 12,
    category:"Accessories",
    img: "images/acc/4.jpg",
    title: "Card 12 Title",
    description: "This is a description for Card 4",
    email: "example@email.com",
  },
  {
    id: 13,
    category:"Accessories",
    img: "images/acc/5.jpg",
    title: "Card 13 Title",
    description: "This is a description for Card 5",
    email: "example@email.com",
  },
  {
    id: 14,
    category:"Accessories",
    img: "images/acc/6.jpg",
    title: "Card 14 Title",
    description: "This is a description for Card 5",
    email: "example@email.com",
  },
  {
    id: 15,
    category:"Accessories",
    img: "images/acc/7.jpg",
    title: "Card 15 Title",
    description: "This is a description for Card 5",
    email: "example@email.com",
  },
  {
    id: 16,
    category:"Accessories",
    img: "images/acc/8.jpg",
    title: "Card 16 Title",
    description: "This is a description for Card 5",
    email: "example@email.com",
  },
  {
    id: 17,
    category:"bags",
    img: "images/bags/1.jpg",
    title: "Card 17 Title",
    description: "This is a description for Card 1",
    email: "example@email.com",
  },
  {
    id: 18,
    category:"bags",
    img: "images/bags/2.jpg",
    title: "Card 18 Title",
    description: "This is a description for Card 2",
    email: "example@email.com",
  },
  {
    id: 19,
    category:"bags",
    img: "images/bags/3.jpg",
    title: "Card 19 Title",
    description: "This is a description for Card 3",
    email: "example@email.com",
  },
  {
    id: 20,
    category:"bags",
    img: "images/bags/4.jpg",
    title: "Card 20 Title",
    description: "This is a description for Card 4",
    email: "example@email.com",
  },
  {
    id: 21,
    category:"bags",
    img: "images/bags/5.jpg",
    title: "Card 21 Title",
    description: "This is a description for Card 5",
    email: "example@email.com",
  },
  {
    id: 22,
    category:"bags",
    img: "images/bags/6.jpg",
    title: "Card 22 Title",
    description: "This is a description for Card 5",
    email: "example@email.com",
  },
  {
    id: 23,
    category:"bags",
    img: "images/bags/7.jpg",
    title: "Card 23 Title",
    description: "This is a description for Card 5",
    email: "example@email.com",
  },
  {
    id: 24,
    category:"bags",
    img: "images/bags/8.jpg",
    title: "Card 24 Title",
    description: "This is a description for Card 5",
    email: "example@email.com",
  },
];

export default productData;


